name: "Create .env.local"
description: "Create a .env.local file and populate it with secrets"

on: workflow_call

runs:
  using: "composite"
  steps:
    - name: Create .env.local
      shell: bash
      run: |
        if [[ -n "${{ secrets.COINGECKO_API_KEY }}" ]]; then
          echo COINGECKO_API_KEY=${{ secrets.COINGECKO_API_KEY }} >> .env.local
        fi
        if [[ -n "${{ secrets.NEAR_NODE_URL }}" ]]; then
          echo NEAR_NODE_URL=${{ secrets.NEAR_NODE_URL }} >> .env.local
        fi
