name: Build PROD - Frontend

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    steps:
      - name: test
        uses: ./.github/actions/test
